"""
This type stub file was generated by pyright.
"""

nsmap = ...
def process_args(): # -> Namespace:
    ...

def qn(tag): # -> str:
    """
    Stands for 'qualified name', a utility function to turn a namespace
    prefixed tag name into a Clark-notation qualified tag name for lxml. For
    example, ``qn('p:cSld')`` returns ``'{http://schemas.../main}cSld'``.
    Source: https://github.com/python-openxml/python-docx/
    """
    ...

def xml2text(xml): # -> str | LiteralString:
    """
    A string representing the textual content of this run, with content
    child elements like ``<w:tab/>`` translated to their Python
    equivalent.
    Adapted from: https://github.com/python-openxml/python-docx/
    """
    ...

def process(docx, img_dir=...): # -> LiteralString | str:
    ...

if __name__ == '__main__':
    args = ...
    text = ...
